<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BsFile\Module'                        => __DIR__ . '/Module.php',
    'BsFile\Controller\SkeletonController' => __DIR__ . '/src/BsFile/Controller/SkeletonController.php',
    'BsFileTest\Framework\TestCase'        => __DIR__ . '/tests/BsFile/Framework/TestCase.php',
    'BsFileTest\SampleTest'                => __DIR__ . '/tests/BsFile/SampleTest.php',
);
